# Generated by Django 5.0 on 2023-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=4096)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
    ]
