# Generated by Django 5.0 on 2024-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
    ]
